### PR TITLE
feat(ci): add goimports sorting lint

### PR DESCRIPTION
**Pull request by ronething**
- Unify package import order for easy code reading
- ref: https://github.com/taikoxyz/taiko-client/actions/runs/8766774478/job/24059285940?pr=734

### CODE REVIEW

**Comment by mask-pp** [comment]
Sorry, our formatting does need to be improved, but I don't agree with this PR that overly complicates this function. I think several commands should be able to do it directly.

**Comment by ronething** [comment]
@mask-pp Hi, thanks for you reply.

> but I don't agree with this PR that overly complicates this function.

But I'd like to know what the complexities are. The main changes are in the `test.yaml` and the sort import script file. Other Go files have been automatically modified by executing make sort-import. 

The reason for adding the sort import lint to `test.yaml` is to ensure that everyone can sort import go files before PR merged.

ref:
-  https://github.com/taikoxyz/taiko-client/pull/734/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88
- https://github.com/taikoxyz/taiko-client/pull/734/files#diff-ba7978b8604d37523bccb0d1e2fa66a61c4a4528eeae606907dc2e28bd7395ab

> I think several commands should be able to do it directly.

what's your option, only sort import go files and add command to Makefile?

**Comment by mask-pp** [comment]
> @mask-pp Hi, thanks for you reply.
> 
> > but I don't agree with this PR that overly complicates this function.
> 
> But I'd like to know what the complexities are. The main changes are in the `test.yaml` and the sort import script file. Other Go files have been automatically modified by executing `make sort-import`.
> 
> The reason for adding the sort import lint to `test.yaml` is to ensure that everyone can sort import go files before PR merged.
> 
> ref:
> 
> * https://github.com/taikoxyz/taiko-client/pull/734/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88
> * https://github.com/taikoxyz/taiko-client/pull/734/files#diff-ba7978b8604d37523bccb0d1e2fa66a61c4a4528eeae606907dc2e28bd7395ab
> 
> > I think several commands should be able to do it directly.
> 
> what's your option, only sort import go files and add command to Makefile?

Cmd `goimports -local "github.com/taikoxyz/taiko-client" -w ./` is enough.

**Comment by ronething** [comment]
> Cmd goimports -local "github.com/taikoxyz/taiko-client" -w ./ is enough.

@mask-pp Maybe not, i use `goimports -local "github.com/taikoxyz/taiko-client" -w ./`, and `prover/event_handler/block_proposed_test.go` result is like below.

In fact, github.com/taikoxyz/taiko-client should need the same group here, but it just adds a blank line.

image

and i see the same result in your PR.  https://github.com/taikoxyz/taiko-client/pull/740/files#diff-e985b5d04a4e6999752689f555f94f1cafc80b71f7f34df5f9c98712f7940234

if we use `https://github.com/incu6us/goimports-reviser`, it will have the right result.

ref: https://github.com/taikoxyz/taiko-client/pull/734/files#diff-e985b5d04a4e6999752689f555f94f1cafc80b71f7f34df5f9c98712f7940234

**Pull request closed without merging**
